service: aws-nodejs # NOTE: update this with your service name

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/books
    - Effect: Allow
      Action: execute-app:Invoke
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/books

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      fetch_books_api: https://wfi698quki.execute-api.us-west-2.amazonaws.com/dev/books      
      search_books_api: https://wfi698quki.execute-api.us-west-2.amazonaws.com/dev/books/search      

  fetch-books:
    handler: functions/fetch-books.handler
    events:
      - http:
          path: /books/
          method: get
          authorizer: aws_iam
    environment:
      books_table: books

  search-books:
    handler: functions/search-books.handler
    events:
      - http:
          path: /books/search
          method: post
    environment:
      books_table: books    

resources:
  Resources:
    libraryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: books
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1